---

- name: Make sure the deploy group are present
  group: name={{deploy_group}}

- name: Make sure the deploy user are present
  user: name={{deploy_user}} system=yes

- name: Ensure deploy dirs exists
  file: path={{item}} state=directory mode={{deploy_mode}} owner={{deploy_user}} group={{deploy_group}}
  when: item not in deploy_dir_skip
  with_items:
      - "{{deploy_dir}}"
      - "{{deploy_etc_dir}}"
      - "{{deploy_log_dir}}"
      - "{{deploy_run_dir}}"
      - "{{deploy_bin_dir}}"
      - "{{deploy_src_dir}}"
